Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,29 +1,45 @@
 name: Check Django Migrations
 
-on: merge_group
+on: 
+  push:
+    branches-ignore:
+      - main
 
 jobs:
   migration-check:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check commit message
+      run: |
+        if [[ $(git log --format=%B -n 1 ${{ github.sha }}) == *"Merge branch"* ]]; then
+          echo "Commit message matches."
+        else
+          exit 78  # Exit code 78 will stop the workflow without failing it.
+        fi
+
     - name: Checkout code
-      uses: actions/checkout@v2
+      if: success()
+      uses: actions/checkout@v4
 
     - name: Set up Python
+      if: success()
       uses: actions/setup-python@v3
       with:
-        python-version: 3.8  # Adjust the Python version as needed
+        python-version: 3.9  # Adjust the Python version as needed
 
     - name: Install dependencies
+      if: success()
       run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt  # Adjust the path to your requirements file
 
     - name: Check migrations
+      if: success()
       run: |
         python manage.py makemigrations --check --dry-run
 
     - name: Validate migrations
+      if: success()
       run: |
         python manage.py migrate --check
